nc = input('Digite seu nome completo: ').strip()
print('Seu nome completo com todas as letras maiusculas fica "{}."'.format(nc.upper()))
print('Com todas as letras minusculas fica "{}"'.format(nc.lower()))
#ncs = nc.replace(' ', '')
#print('Seu nome completo tem {} letras sem considerar espaços.'.format(len(ncs)))
print('Seu nome completo tem {} letras sem considerar espaços.'.format(len(nc) - nc.count(' ')))
#nspl = nc.split()
#print('Seu primeiro nome tem {} letras.'.format(len(nspl [0])))
print('Seu primeiro nome tem {} letras.'.format(nc.find(' ')))